name: Master Branch CI

on:
  push:
    branches:
      - 'master'
    paths:
      - "moviebuffs-data-importer/**"
      - "moviebuffs-gatling-tests/**"
      - "moviebuffs-service/**"
      - "moviebuffs-tools/**"

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B clean install -Pfull

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: 'adopt'
          cache: 'maven'
      - name: Package with Maven
        run: ./mvnw -B clean install -DskipTests --file pom.xml
        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: dockertmt/moviebuffs
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          workdir: ./moviebuffs-service
          default_branch: master
          tags: "latest"
          buildoptions: "--compress --force-rm"
