name: React CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - "moviebuffs-ui-react/**"
  pull_request:
    branches: [ master ]
    paths:
      - "moviebuffs-ui-react/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    timeout-minutes: 10
    name: Build and Test React App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "moviebuffs-ui-react"
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5.0.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5.5.1

    - name: Build
      run: npm run build
